
-- ============================================================================
-- MASTER SCHEMA SCRIPT - HALAQAH ATTENDANCE SYSTEM
-- Jalankan script ini di SQL Editor Supabase untuk membuat ulang database dari 0.
-- ============================================================================

-- 1. DROP TABLES (URUTAN PENTING KARENA RELASI)
-- Hapus tabel lama jika ada (untuk reset bersih)
DROP TABLE IF EXISTS "public"."student_progress";
DROP TABLE IF EXISTS "public"."attendance";
DROP TABLE IF EXISTS "public"."halaqah_santri";
DROP TABLE IF EXISTS "public"."halaqah";
DROP TABLE IF EXISTS "public"."wali_kelas";
DROP TABLE IF EXISTS "public"."chat";
DROP TABLE IF EXISTS "public"."informasi";
DROP TABLE IF EXISTS "public"."santri";
DROP TABLE IF EXISTS "public"."musammi";

-- 2. DROP ENUMS
DROP TYPE IF EXISTS "public"."marhalah_enum";
DROP TYPE IF EXISTS "public"."waktu_enum";
DROP TYPE IF EXISTS "public"."attendance_status_enum";
DROP TYPE IF EXISTS "public"."peran_enum";
DROP TYPE IF EXISTS "public"."halaqah_type_enum";

-- 3. CREATE ENUMS (Tipe Data Khusus)
CREATE TYPE "public"."marhalah_enum" AS ENUM ('Mutawassithah', 'Aliyah', 'Jamiah');
CREATE TYPE "public"."waktu_enum" AS ENUM ('Shubuh', 'Dhuha', 'Ashar', 'Isya');
CREATE TYPE "public"."attendance_status_enum" AS ENUM ('Hadir', 'Izin', 'Sakit', 'Alpa', 'Terlambat');
CREATE TYPE "public"."peran_enum" AS ENUM ('Santri', 'Musammi');
CREATE TYPE "public"."halaqah_type_enum" AS ENUM ('Halaqah Utama', 'Halaqah Pagi');

-- 4. CREATE TABLES

-- Tabel Santri
CREATE TABLE "public"."santri" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "nama" text NOT NULL,
    "marhalah" "public"."marhalah_enum" NOT NULL,
    "kelas" text NOT NULL,
    "kode" text UNIQUE -- Kode unik misal S-001
);

-- Tabel Musammi (Pengajar)
CREATE TABLE "public"."musammi" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "nama" text NOT NULL,
    "marhalah" "public"."marhalah_enum" NOT NULL,
    "kelas" text NOT NULL, -- Kelas binaan atau default
    "kode" text UNIQUE, -- Kode unik misal M-001
    "no_hp" text
);

-- Tabel Wali Kelas
CREATE TABLE "public"."wali_kelas" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "nama" text NOT NULL,
    "marhalah" text NOT NULL, -- Text agar fleksibel atau bisa pakai enum
    "kelas" text NOT NULL,
    "no_hp" text
);

-- Tabel Halaqah (Kelompok)
CREATE TABLE "public"."halaqah" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "nama" text NOT NULL,
    "musammi_id" bigint REFERENCES "public"."musammi"("id") ON DELETE SET NULL,
    "marhalah" "public"."marhalah_enum" NOT NULL,
    "jenis" text NOT NULL, -- Text agar bisa custom jenis
    "waktu" "public"."waktu_enum"[] -- Array of Waktu
);

-- Tabel Pivot: Anggota Halaqah (Many-to-Many antara Halaqah dan Santri)
CREATE TABLE "public"."halaqah_santri" (
    "halaqah_id" bigint REFERENCES "public"."halaqah"("id") ON DELETE CASCADE NOT NULL,
    "santri_id" bigint REFERENCES "public"."santri"("id") ON DELETE CASCADE NOT NULL,
    PRIMARY KEY ("halaqah_id", "santri_id")
);

-- Tabel Absensi
CREATE TABLE "public"."attendance" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "date" text NOT NULL, -- Format YYYY-MM-DD
    "waktu" "public"."waktu_enum" NOT NULL,
    "person_id" bigint NOT NULL, -- ID Santri atau Musammi
    "peran" "public"."peran_enum" NOT NULL,
    "status" "public"."attendance_status_enum" NOT NULL,
    "halaqah_id" bigint REFERENCES "public"."halaqah"("id") ON DELETE SET NULL
);

-- Tabel Perkembangan Santri (Hafalan/Murojaah/Ziyadah)
CREATE TABLE "public"."student_progress" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "santri_id" bigint REFERENCES "public"."santri"("id") ON DELETE CASCADE NOT NULL,
    "month_key" text NOT NULL, -- Format YYYY-MM
    "progress_type" text NOT NULL, -- "Hafalan", "Murojaah", "Ziyadah"
    "value" text NOT NULL,
    CONSTRAINT "unique_progress_entry" UNIQUE ("santri_id", "month_key", "progress_type")
);

-- Tabel Informasi
CREATE TABLE "public"."informasi" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "title" text NOT NULL,
    "content" text NOT NULL,
    "author_email" text,
    "is_pinned" boolean DEFAULT false
);

-- Tabel Chat
CREATE TABLE "public"."chat" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "content" text NOT NULL,
    "sender_email" text NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL
);

-- 5. SECURITY & RLS (Row Level Security)
-- Mengaktifkan keamanan tabel
ALTER TABLE "public"."santri" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."musammi" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."wali_kelas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."halaqah" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."halaqah_santri" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."student_progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."informasi" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."chat" ENABLE ROW LEVEL SECURITY;

-- 6. POLICIES (Aturan Akses)
-- Catatan: Policy ini bersifat "Permissive" untuk user terautentikasi demi kemudahan.
-- Anda bisa memperketatnya nanti.

-- Helper Macro: Allow Authenticated Users Full Access
CREATE POLICY "Allow all for authenticated users" ON "public"."santri" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated users" ON "public"."musammi" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated users" ON "public"."wali_kelas" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated users" ON "public"."halaqah" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated users" ON "public"."halaqah_santri" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated users" ON "public"."attendance" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated users" ON "public"."student_progress" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated users" ON "public"."informasi" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Chat Policies (Lebih spesifik)
CREATE POLICY "Enable read access for all users" ON "public"."chat" FOR SELECT TO public USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON "public"."chat" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable delete for message owner" ON "public"."chat" FOR DELETE TO authenticated USING ((auth.jwt() ->> 'email') = sender_email);

-- 7. REALTIME
-- Mengaktifkan fitur realtime agar chat dan dashboard update otomatis
ALTER PUBLICATION supabase_realtime ADD TABLE "public"."chat";
ALTER PUBLICATION supabase_realtime ADD TABLE "public"."attendance";

-- SELESAI.
