
-- ============================================================================
-- MULTI-TENANT SCHEMA SCRIPT
-- Jalankan ini untuk mengubah sistem menjadi Multi-Ma'had.
-- ============================================================================

-- 1. BERSIHKAN TABEL LAMA (Hati-hati, data lama akan hilang jika dijalankan di production)
DROP TABLE IF EXISTS "public"."student_progress";
DROP TABLE IF EXISTS "public"."attendance";
DROP TABLE IF EXISTS "public"."halaqah_santri";
DROP TABLE IF EXISTS "public"."halaqah";
DROP TABLE IF EXISTS "public"."wali_kelas";
DROP TABLE IF EXISTS "public"."chat";
DROP TABLE IF EXISTS "public"."informasi";
DROP TABLE IF EXISTS "public"."santri";
DROP TABLE IF EXISTS "public"."musammi";
DROP TABLE IF EXISTS "public"."profiles";
DROP TABLE IF EXISTS "public"."organizations";

-- 2. TABEL ORGANISASI (MA'HAD)
CREATE TABLE "public"."organizations" (
    "id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "name" text NOT NULL DEFAULT 'Ma''had Al Faruq',
    "logo_url" text DEFAULT 'https://i.ibb.co.com/KcYyzZRz/Tanpa-judul-1080-x-1080-piksel-20260116-084021-0000.png',
    "address" text
);

-- 3. TABEL PROFIL USER (Mapping User Auth -> Organisasi)
CREATE TABLE "public"."profiles" (
    "id" uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    "organization_id" uuid REFERENCES "public"."organizations"("id") ON DELETE CASCADE,
    "full_name" text,
    "role" text DEFAULT 'admin'
);

-- 4. BUAT ULANG TABEL DATA DENGAN KOLOM ORGANIZATION_ID

-- ENUMS (Tetap sama)
DROP TYPE IF EXISTS "public"."marhalah_enum";
DROP TYPE IF EXISTS "public"."waktu_enum";
DROP TYPE IF EXISTS "public"."attendance_status_enum";
DROP TYPE IF EXISTS "public"."peran_enum";
DROP TYPE IF EXISTS "public"."halaqah_type_enum";

CREATE TYPE "public"."marhalah_enum" AS ENUM ('Mutawassithah', 'Aliyah', 'Jamiah');
CREATE TYPE "public"."waktu_enum" AS ENUM ('Shubuh', 'Dhuha', 'Ashar', 'Isya');
CREATE TYPE "public"."attendance_status_enum" AS ENUM ('Hadir', 'Izin', 'Sakit', 'Alpa', 'Terlambat');
CREATE TYPE "public"."peran_enum" AS ENUM ('Santri', 'Musammi');
CREATE TYPE "public"."halaqah_type_enum" AS ENUM ('Halaqah Utama', 'Halaqah Pagi');

-- Tabel Santri
CREATE TABLE "public"."santri" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" uuid REFERENCES "public"."organizations"("id") NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "nama" text NOT NULL,
    "marhalah" "public"."marhalah_enum" NOT NULL,
    "kelas" text NOT NULL,
    "kode" text
);

-- Tabel Musammi
CREATE TABLE "public"."musammi" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" uuid REFERENCES "public"."organizations"("id") NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "nama" text NOT NULL,
    "marhalah" "public"."marhalah_enum" NOT NULL,
    "kelas" text NOT NULL,
    "kode" text,
    "no_hp" text
);

-- Tabel Wali Kelas
CREATE TABLE "public"."wali_kelas" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" uuid REFERENCES "public"."organizations"("id") NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "nama" text NOT NULL,
    "marhalah" text NOT NULL,
    "kelas" text NOT NULL,
    "no_hp" text
);

-- Tabel Halaqah
CREATE TABLE "public"."halaqah" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" uuid REFERENCES "public"."organizations"("id") NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "nama" text NOT NULL,
    "musammi_id" bigint REFERENCES "public"."musammi"("id") ON DELETE SET NULL,
    "marhalah" "public"."marhalah_enum" NOT NULL,
    "jenis" text NOT NULL,
    "waktu" "public"."waktu_enum"[]
);

-- Tabel Halaqah Santri (Pivot)
CREATE TABLE "public"."halaqah_santri" (
    "organization_id" uuid REFERENCES "public"."organizations"("id") NOT NULL,
    "halaqah_id" bigint REFERENCES "public"."halaqah"("id") ON DELETE CASCADE NOT NULL,
    "santri_id" bigint REFERENCES "public"."santri"("id") ON DELETE CASCADE NOT NULL,
    PRIMARY KEY ("halaqah_id", "santri_id")
);

-- Tabel Attendance
CREATE TABLE "public"."attendance" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" uuid REFERENCES "public"."organizations"("id") NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "date" text NOT NULL,
    "waktu" "public"."waktu_enum" NOT NULL,
    "person_id" bigint NOT NULL,
    "peran" "public"."peran_enum" NOT NULL,
    "status" "public"."attendance_status_enum" NOT NULL,
    "halaqah_id" bigint REFERENCES "public"."halaqah"("id") ON DELETE SET NULL
);

-- Tabel Student Progress
CREATE TABLE "public"."student_progress" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" uuid REFERENCES "public"."organizations"("id") NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "santri_id" bigint REFERENCES "public"."santri"("id") ON DELETE CASCADE NOT NULL,
    "month_key" text NOT NULL,
    "progress_type" text NOT NULL,
    "value" text NOT NULL,
    CONSTRAINT "unique_progress_entry" UNIQUE ("santri_id", "month_key", "progress_type")
);

-- Tabel Informasi
CREATE TABLE "public"."informasi" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" uuid REFERENCES "public"."organizations"("id") NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "title" text NOT NULL,
    "content" text NOT NULL,
    "author_email" text,
    "is_pinned" boolean DEFAULT false
);

-- Tabel Chat
CREATE TABLE "public"."chat" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" uuid REFERENCES "public"."organizations"("id") NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "content" text NOT NULL,
    "sender_email" text NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL
);

-- 5. ROW LEVEL SECURITY (RLS) - INTI DARI MULTI-TENANCY
-- Kita aktifkan RLS di semua tabel, dan buat policy agar user hanya bisa akses data
-- dimana organization_id tabel == organization_id user di tabel profiles.

ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE santri ENABLE ROW LEVEL SECURITY;
ALTER TABLE musammi ENABLE ROW LEVEL SECURITY;
ALTER TABLE wali_kelas ENABLE ROW LEVEL SECURITY;
ALTER TABLE halaqah ENABLE ROW LEVEL SECURITY;
ALTER TABLE halaqah_santri ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE informasi ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat ENABLE ROW LEVEL SECURITY;

-- Policy Helper Function (Optional, tapi kita hardcode di policy untuk kompatibilitas basic)
-- Logic: Check if the row's organization_id matches the current user's profile organization_id

-- 1. Organizations Policy
CREATE POLICY "Users can view their own organization" ON organizations
    FOR SELECT USING (id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));

-- 2. Profiles Policy
CREATE POLICY "Users can view their own profile" ON profiles
    FOR SELECT USING (id = auth.uid());
-- Trigger otomatis insert profile akan bypass RLS, jadi aman.

-- 3. Data Tables Policy Template (Diterapkan ke semua tabel data)
CREATE POLICY "Tenant Isolation Santri" ON santri
    USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()))
    WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Tenant Isolation Musammi" ON musammi
    USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()))
    WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Tenant Isolation WaliKelas" ON wali_kelas
    USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()))
    WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Tenant Isolation Halaqah" ON halaqah
    USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()))
    WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Tenant Isolation HalaqahSantri" ON halaqah_santri
    USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()))
    WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Tenant Isolation Attendance" ON attendance
    USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()))
    WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Tenant Isolation Progress" ON student_progress
    USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()))
    WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Tenant Isolation Informasi" ON informasi
    USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()))
    WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));

CREATE POLICY "Tenant Isolation Chat" ON chat
    USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()))
    WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));


-- 6. TRIGGER OTOMATIS: BUAT ORGANISASI BARU SAAT SIGN UP
-- Setiap user baru akan dibuatkan Organisasi baru secara otomatis.
-- Jika ingin sistem "Invite", logikanya beda, tapi ini cara termudah agar website bisa dipakai siapa saja.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  new_org_id uuid;
BEGIN
  -- 1. Buat Organisasi Baru
  INSERT INTO public.organizations (name)
  VALUES ('Ma''had Baru')
  RETURNING id INTO new_org_id;

  -- 2. Buat Profil User dan link ke Organisasi tadi
  INSERT INTO public.profiles (id, organization_id, full_name)
  VALUES (new.id, new_org_id, new.raw_user_meta_data->>'full_name');

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind trigger ke tabel auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 7. REALTIME
ALTER PUBLICATION supabase_realtime ADD TABLE "public"."chat";
ALTER PUBLICATION supabase_realtime ADD TABLE "public"."attendance";
