
-- ============================================================================
-- SCRIPT UNTUK FITUR TARGET KELAS
-- Jalankan ini di SQL Editor Supabase
-- ============================================================================

-- 1. Buat Tabel Target Kelas
CREATE TABLE IF NOT EXISTS "public"."class_targets" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" uuid REFERENCES "public"."organizations"("id") NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "marhalah" "public"."marhalah_enum" NOT NULL,
    "kelas" text NOT NULL,
    "target_ziyadah" numeric DEFAULT 0,
    "target_murojaah" numeric DEFAULT 0,
    "target_hafalan" numeric DEFAULT 0,
    CONSTRAINT "unique_class_target" UNIQUE ("organization_id", "marhalah", "kelas")
);

-- 2. Enable RLS
ALTER TABLE "public"."class_targets" ENABLE ROW LEVEL SECURITY;

-- 3. Buat Policy (Isolasi per Organisasi)
CREATE POLICY "Tenant Isolation Class Targets" ON "public"."class_targets"
    USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()))
    WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()));

-- Selesai.
